name: Deployment to github pages

on:
  push:
    branches: [ ops/gh-pages ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to ops/gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: ops/gh-pages
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Re-create a copy of .env.dist 
        run: rm -f .env && cp .env.dist .env
      - name: Deploy to Gihub Pages
        run: |
          git config --global user.email ${{secrets.MY_GITHUB_EMAIL}}
          git config --global user.name ${{secrets.MY_GITHUB_USERNAME}}
          git remote set-url origin https://${{secrets.MY_GITHUB_PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.MY_GITHUB_USERNAME}}/${{secrets.MY_GITHUB_REPO_NAME}}.git
          yarn deploy
